apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  labels:
    app: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: sample-app
        #don't want to pull this image from a public registry since it’s only available locally
        #use minikube docker daemon
        imagePullPolicy: Never
        ports:
        - name: web
          containerPort: 8080